name: k2
tag: ''
seed: 42
dataset:
  name: ortho
  root_dir: ../mv_res
  cam_pose_dir: null
  scene: k2
  imSize:
  - 1024
  - 1024
  camera_type: ortho
  apply_mask: true
  camera_params: null
  view_weights:
  - 1.0
  - 0.7
  - 0.4
  - 1.0
  - 0.7
  - 0.4
model:
  name: neus
  radius: 1.0
  num_samples_per_ray: 1024
  train_num_rays: 256
  max_train_num_rays: 8192
  grid_prune: true
  grid_prune_occ_thre: 0.001
  dynamic_ray_sampling: true
  batch_image_sampling: true
  randomized: true
  ray_chunk: 2048
  cos_anneal_end: 20000
  learned_background: false
  background_color: black
  variance:
    init_val: 0.3
    modulate: false
  geometry:
    name: volume-sdf
    radius: 1.0
    feature_dim: 13
    grad_type: finite_difference
    finite_difference_eps: progressive
    isosurface:
      method: mc
      resolution: 256
      chunk: 2097152
      threshold: 0.0
    xyz_encoding_config:
      otype: ProgressiveBandHashGrid
      n_levels: 10
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 32
      per_level_scale: 1.3195079107728942
      include_xyz: true
      start_level: 4
      start_step: 0
      update_steps: 1000
    mlp_network_config:
      otype: VanillaMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 1
      sphere_init: true
      sphere_init_radius: 0.5
      weight_norm: true
  texture:
    name: volume-radiance
    input_feature_dim: 16
    dir_encoding_config:
      otype: SphericalHarmonics
      degree: 4
    mlp_network_config:
      otype: VanillaMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 2
    color_activation: sigmoid
system:
  name: ortho-neus-system
  loss:
    lambda_rgb_mse: 0.5
    lambda_rgb_l1: 0.0
    lambda_mask: 1.0
    lambda_eikonal: 0.2
    lambda_normal: 1.0
    lambda_3d_normal_smooth: 1.0
    lambda_curvature: 0.0
    lambda_sparsity: 1.0
    lambda_distortion: 0.0
    lambda_distortion_bg: 0.0
    lambda_opaque: 0.0
    sparsity_scale: 100.0
    geo_aware: true
    rgb_p_ratio: 0.8
    normal_p_ratio: 0.8
    mask_p_ratio: 0.9
  optimizer:
    name: AdamW
    args:
      lr: 0.01
      betas:
      - 0.9
      - 0.99
      eps: 1.0e-15
    params:
      geometry:
        lr: 0.001
      texture:
        lr: 0.01
      variance:
        lr: 0.001
  constant_steps: 500
  scheduler:
    name: SequentialLR
    interval: step
    milestones:
    - 500
    schedulers:
    - name: ConstantLR
      args:
        factor: 1.0
        total_iters: 500
    - name: ExponentialLR
      args:
        gamma: 0.9990793899844618
checkpoint:
  save_top_k: -1
  every_n_train_steps: 3000
export:
  chunk_size: 2097152
  export_vertex_color: true
  ortho_scale: 1.0
trainer:
  max_steps: 3000
  log_every_n_steps: 100
  num_sanity_val_steps: 0
  val_check_interval: 4000
  limit_train_batches: 1.0
  limit_val_batches: 2
  enable_progress_bar: true
  precision: 16
cmd_args:
  config: configs/neuralangelo-ortho-wmask.yaml
  gpu: '0'
  resume: null
  resume_weights_only: false
  train: true
  validate: false
  test: false
  predict: false
  exp_dir: '3'
  runs_dir: ./runs
  verbose: false
trial_name: '@20240910-200942'
exp_dir: 3/k2
save_dir: 3/k2/@20240910-200942/save
ckpt_dir: 3/k2/@20240910-200942/ckpt
code_dir: 3/k2/@20240910-200942/code
config_dir: 3/k2/@20240910-200942/config
